<?php

namespace Database\Seeders;

use App\Models\School;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schools_data = [
            ['school_code' => '001/I/SKL-CPK','school_name' => 'KOBER AL HIDAYAH','address' => 'Dsn. Balandongan Rt.03 Rw. 02 Ds. Mandalare Kec. Panjalu Kab. Ciamis','school_level' => 'I','pic_name' => 'Imas Samrotul Fuadah, S.Pd','pic_position' => 'Kepala Sekolah','pic_phone_number' => '81222271307','pic_email' => 'imassamrotul09@gmail.com','hm_name' => 'Imas Samrotul Fuadah, S.Pd','hm_phone_number' => '81222271307','hm_email' => 'imassamrotul09@gmail.com'],
            ['school_code' => '002/III/SKL-CPK','school_name' => 'SDN 4 CIOMAS','address' => 'Dsn. Ciomas Landeuh Rt 20/ 19 Desa Ciomas Kec. Panjalu','school_level' => 'III','pic_name' => 'Herlin, S.P','pic_position' => 'Guru','pic_phone_number' => '81321261283','pic_email' => 'herlin521@guru.sd.belajar.id','hm_name' => 'Lies Andriani, S.Pd.SD','hm_phone_number' => '82117167727','hm_email' => 'lies.andriani14@admin.sd.belajar.id'],
            ['school_code' => '003/I/SKL-CPK','school_name' => 'KOBER RIYADLUL JANNAH','address' => 'Dusun Baros Rt 16 Rw 07 Desa Ciomas Kecamatan Panjalu Kabupaten Ciamis','school_level' => 'I','pic_name' => 'Syifa Iklima','pic_position' => 'Operator/ Guru','pic_phone_number' => '85861023832','pic_email' => 'syifaiklima6@gmail.com','hm_name' => 'Elis Susilawati S.Pd','hm_phone_number' => '81312103649','hm_email' => 'elissusilawati1971@gmail.com'],
            ['school_code' => '004/III/SKL-CPK','school_name' => 'SD NEGERI 7 PANJALU','address' => 'Dsn. Parcariang Desa/Kec. Panjalu Kab. Ciamis','school_level' => 'III','pic_name' => 'Guntur Irianto, S.Pd.I','pic_position' => 'Guru','pic_phone_number' => '82120034993','pic_email' => 'gunturgamarazta@gmail.com','hm_name' => 'Rina Risnawati, S.Pd','hm_phone_number' => '82219119925','hm_email' => 'rinarisnawati823@gmail.com'],
            ['school_code' => '005/II/SKL-CPK','school_name' => 'TK NURUL HUDA','address' => 'Dusun Banjar Rt 20 Rw 07','school_level' => 'II','pic_name' => 'Aan Nurjasanah','pic_position' => 'Guru','pic_phone_number' => '81298817871','pic_email' => 'aanelestohary14@gmail.com','hm_name' => 'Encep Muhamad Romli, S. H','hm_phone_number' => '852237037777','hm_email' => 'nh.daarulyatama@gmail.com'],
            ['school_code' => '006/III/SKL-CPK','school_name' => 'SDN 2 MANDALARE','address' => 'Balandongan','school_level' => 'III','pic_name' => 'EVI NOVIANA, S.Pd.I.','pic_position' => 'GURU','pic_phone_number' => '85295325932','pic_email' => 'evinoviana699@gmail.com','hm_name' => 'DEDE RUDI, S.Pd.I.','hm_phone_number' => '82214297795','hm_email' => 'kertamandala.3@gmail.com'],
            ['school_code' => '007/III/SKL-CPK','school_name' => 'SDN 3 KERTAMANDALA','address' => 'Dusun Banjarlangenan Desa Kertamandala','school_level' => 'III','pic_name' => 'TUTI SUGIARTI, S.Pd.I','pic_position' => 'GURU','pic_phone_number' => '81221425163','pic_email' => 'sugiartituti8@gmail.com','hm_name' => 'UJANG DARWANA, S.Pd','hm_phone_number' => '81323103214','hm_email' => 'ujangdarwana@gmail.com'],
            ['school_code' => '008/I/SKL-CPK','school_name' => 'KOBER MIFTAHUL HUDA','address' => 'Dsn Cikareo Ds. Ciomas Kec.Panjalu Kab. Ciamis','school_level' => 'I','pic_name' => 'Yanti Barokah lastri','pic_position' => 'Guru','pic_phone_number' => '85211813893','pic_email' => 'yantibarokah942@gmail.com','hm_name' => 'Endih Solehudin','hm_phone_number' => '81222084604','hm_email' => 'endihsolehudin81@gmail.com'],
            ['school_code' => '009/I/SKL-CPK','school_name' => 'KOBER AL-ISTIQOMAH','address' => 'Dusun Ciomas Rt 003/Rw 002 Desa Ciomas Kec. Panjalu Kab. Ciamis','school_level' => 'I','pic_name' => 'Pipih Ratnasari, S. Pd','pic_position' => 'Kepala Sekolah','pic_phone_number' => '85322499507','pic_email' => 'pipihratnasari377@gmail.com','hm_name' => 'Pipih Ratnasari, S. Pd','hm_phone_number' => '85322499507','hm_email' => 'pipihratnasari377@gmail.com'],
            ['school_code' => '010/II/SKL-CPK','school_name' => 'TKA. NURUL ULUM','address' => 'Dusun Selauni, Jalan Cicangkrung Rt.015/Rw.005 Kertamandala - Panjalu - Ciamis','school_level' => 'II','pic_name' => 'Eva Suryani','pic_position' => 'Guru','pic_phone_number' => '8979729133','pic_email' => 'evafaal@gmail.com','hm_name' => 'Zulfa ila nurazizah','hm_phone_number' => '82118827478','hm_email' => 'Zulfailanurazizah74@gmail.com'],
            ['school_code' => '011/II/SKL-CPK','school_name' => 'RA AL HIKMAH','address' => 'Jln.Panjalu-Kawali, Ds.Ciomas, Kec.Panjalu, Kab.Ciamis','school_level' => 'II','pic_name' => 'Oom Maryani, S.Pd.I','pic_position' => 'Kepala Sekolah','pic_phone_number' => '85723690300','pic_email' => 'jj0434072@gmail.com','hm_name' => 'Oom Maryani, S.Pd.I','hm_phone_number' => '85723690300','hm_email' => 'jj0434072@gmail.com'],
            ['school_code' => '012/III/SKL-CPK','school_name' => 'MIS BABUSSALAM','address' => 'Dusun Hanjatan Desa Ciomas Kecamatan Panjalu Kabupaten Ciamis','school_level' => 'III','pic_name' => 'Sri Ratnasari, S.Pd.','pic_position' => 'Guru','pic_phone_number' => '85890767564','pic_email' => 'sriratna532@gmail.com','hm_name' => 'Drs. Abdul Haris, M.Pd.I','hm_phone_number' => '82115587753','hm_email' => 'pkkmmisbabussalam@gmail.com'],
            ['school_code' => '013/I/SKL-CPK','school_name' => 'KOBER BABUSSALAM','address' => 'Dusun Hanjatan Rt/Rw 21/10 Desa Ciomas,Kecamatan Panjalu,Kabupaten Ciamis','school_level' => 'I','pic_name' => 'Utin Sutinah','pic_position' => 'Guru','pic_phone_number' => '85320693322','pic_email' => 'sutinahutin3@gmail.com','hm_name' => 'Dudu Abdul Kamil','hm_phone_number' => '0','hm_email' => 'sutinahutin3@gmail.com'],
            ['school_code' => '014/III/SKL-CPK','school_name' => 'SDN 2 KERTAMANDALA','address' => 'Dusun Cibugur, Rt. 004/Rw, 001, Desa Kertamandala, Kec. Panjalu, Kab. Ciamis','school_level' => 'III','pic_name' => 'Anggie Prabusenja, S.Pd.I','pic_position' => 'Guru','pic_phone_number' => '81294949705','pic_email' => 'anggieprabusenja88@guru.sd.belajar.id','hm_name' => 'Ayi Ruhenda, S.Pd.SD','hm_phone_number' => '85221488930','hm_email' => 'ayiruhenda61@admin.sd.belajar.id'],
            ['school_code' => '015/II/SKL-CPK','school_name' => 'TK AL FALAH','address' => 'Kp.Kertabraya, Desa Kertandala,Kec.Panjalu,Kab.Ciamis','school_level' => 'II','pic_name' => 'Ade sri sadiah','pic_position' => 'Guru','pic_phone_number' => '85310718347','pic_email' => 'ilhamazamfariz@gmail.com','hm_name' => 'Ahmad abdul qosim','hm_phone_number' => '81323339663','hm_email' => 'tabrayaoke@gmail.com'],
            ['school_code' => '016/IV/SKL-CPK','school_name' => 'SMP IT AL-AMANAH','address' => 'Dusun Garahang Rt 29 Rw 13 Desa Panjalu Kec.Panjalu Kab.Ciamis','school_level' => 'IV','pic_name' => 'Zakaria S.Pd','pic_position' => 'Kepala Sekolah','pic_phone_number' => '82310368533','pic_email' => 'lactobacilusprotektus@gmail.com','hm_name' => 'Zakaria S.Pd','hm_phone_number' => '82310368533','hm_email' => 'lactobacilusprotektus@gmail.com'],
            ['school_code' => '017/I/SKL-CPK','school_name' => 'KOBER NURLUKMAN 2','address' => 'Dusun Cibungur Rt/Rw 03/01 Desa.Kertamandala Kec.Panjalu Kab.Ciamis','school_level' => 'I','pic_name' => 'Widi febriani','pic_position' => 'Guru','pic_phone_number' => '85927322643','pic_email' => 'febrianiwidi44@gmail.com','hm_name' => 'Junah yuningsih s.pd','hm_phone_number' => '82129465054','hm_email' => 'febrianiwidi44@gmail.com'],
            ['school_code' => '018/I/SKL-CPK','school_name' => 'KOBER RIYADUL HUDA','address' => 'Dusun Bojong Sari Rt/Rw 26/12, Desa Ciomas, Kec. Panjalu, Kab. Ciamis, Prov. Jawa Barat','school_level' => 'I','pic_name' => 'Ai Eti Sukmawati','pic_position' => 'Guru Pengajar','pic_phone_number' => '82315899282','pic_email' => 'etisukmawati406@gmail.com','hm_name' => 'Tatang','hm_phone_number' => '85223319144','hm_email' => 'Tatanghaji290@gmail.com'],
            ['school_code' => '019/I/SKL-CPK','school_name' => 'KOBER AL HIKMAH','address' => 'Dusun Paricariang Desa Panjalu','school_level' => 'I','pic_name' => 'Ai Sukaesih, S.Pd','pic_position' => 'Kepala Sekolah','pic_phone_number' => '81321525811','pic_email' => 'aisukaesih81@gmail.com','hm_name' => 'Ai Sukaesih, S.Pd','hm_phone_number' => '81321525811','hm_email' => 'aisukaesih81@gmail.com'],
            ['school_code' => '020/II/SKL-CPK','school_name' => 'RA NURUL HUDA','address' => 'Dusun Bojongsereh Rt/Rw.33/15 Desa Ciomas Kecamatan Panjalu','school_level' => 'II','pic_name' => 'Yuyu yuliati, S.Pd.','pic_position' => 'Kepala sekolah','pic_phone_number' => '82216519098','pic_email' => 'yuyuyuliati1234@gmail.com','hm_name' => 'Yuyu yuliati, S.Pd.','hm_phone_number' => '82216519098','hm_email' => 'yuyuyuliati1234@gmail.com'],
            ['school_code' => '021/II/SKL-CPK','school_name' => 'TK AL-IMAN NUR LUKMAN','address' => 'Dsn Reumalega Rt 08/02 Ds Kertamandala Kec Panjalu Kab Ciamis','school_level' => 'II','pic_name' => 'Yuli Sulastri Suparman, S.Pd','pic_position' => 'Kepala Sekolah','pic_phone_number' => '81394381961','pic_email' => 'sulastriyuli47@gmail.coma','hm_name' => 'Yuli Sulastri Suparman, S.Pd','hm_phone_number' => '81394381961','hm_email' => 'yuli.sulastri319@admin.paud.belajar.id'],
            ['school_code' => '022/I/SKL-CPK','school_name' => 'PAUD KOBER AL AMIN','address' => 'Dusun Banjar Rt 21 Rw 08 Desa Kertamandala Kec Panjalu Kab Ciamis','school_level' => 'I','pic_name' => 'Ai latifatussadiah','pic_position' => 'Guru','pic_phone_number' => '82219960861','pic_email' => 'ailatifatussadiah@gmail.com','hm_name' => 'Ai latifatussadiah','hm_phone_number' => '82219960861','hm_email' => 'ailatifatussadiah@gmail.com'],
            ['school_code' => '023/II/SKL-CPK','school_name' => 'RA MUSLIMIN PANJALU','address' => 'Jln. Raya Panjalu Dusun Cukangpadung Rt/Rw 008/004 Desa Panjalu, Kec. Panjalu Kab. Ciamis','school_level' => 'II','pic_name' => 'Wida Farida, S. SOS','pic_position' => 'Kepala Sekolah','pic_phone_number' => '81321225216','pic_email' => 'widafaridara@gmail.com','hm_name' => 'Wida Farida, S. SOS','hm_phone_number' => '81321225216','hm_email' => 'widafaridara@gmail.com'],
            ['school_code' => '024/III/SKL-CPK','school_name' => 'SDN 1 KERTAMANDALA','address' => 'Dusun Mandala Rt 17/Rw 06','school_level' => 'III','pic_name' => 'Nopianti,S.Pd.I','pic_position' => 'Guru','pic_phone_number' => '82120316278','pic_email' => 'nopianti04@guru.sd.belajar.id','hm_name' => 'Jaja Subagja,S.Pd','hm_phone_number' => '81323790120','hm_email' => 'jajasubagja19@admin.sd.belajar.id'],
            ['school_code' => '025/III/SKL-CPK','school_name' => 'SDN 3 CIOMAS','address' => 'Dusun Ciceuri Desa Ciomas Kecamatan Panjalu Kab. Ciamis','school_level' => 'III','pic_name' => 'Suci Nurlina, S.Pd.','pic_position' => 'Guru PJOK','pic_phone_number' => '6282126975563','pic_email' => 'sdnciomas376@gmail.com','hm_name' => 'Lela Lusiana, S.Pd.','hm_phone_number' => '85294723793','hm_email' => 'lelalusiana61@admin.sd.belajar.id'],
            ['school_code' => '026/II/SKL-CPK','school_name' => 'RA ALQURAN ALHIDAYAH','address' => 'Dusun Garahang Rt 27 Rw 12 Desa Panjalu Kec.Panjalu Kab.Ciamis','school_level' => 'II','pic_name' => 'Ai Nurhayati','pic_position' => 'Guru kelas','pic_phone_number' => '85221372206','pic_email' => 'hasanjengkol54@gmail.com','hm_name' => 'Ai Sulastri,S.Pd.I','hm_phone_number' => '85320760180','hm_email' => 'aisulastri113@gmail.com'],
            ['school_code' => '027/III/SKL-CPK','school_name' => 'SDN 2 CIOMAS','address' => 'Dusun Bojongsereh Desa Ciomas Kecamatan Panjalu Kabupaten Ciamis','school_level' => 'III','pic_name' => 'ACE DIDIN KOMARUDIN,S.Pd','pic_position' => 'KEPALA SEKOLAH','pic_phone_number' => '6285223299663','pic_email' => 'acedidi04@gmail.com','hm_name' => 'ACE DIDIN KOMARUDIN,S.Pd','hm_phone_number' => '85223299663','hm_email' => 'acedidi04@gmail.com'],
            ['school_code' => '028/I/SKL-CPK','school_name' => 'KOBER NURUL HIKMAH','address' => 'Dusin Tembong Rt 010 / 003 Kertamandala Panjalu Ciamis','school_level' => 'I','pic_name' => 'Nunung','pic_position' => 'Pengelola','pic_phone_number' => '81220315524','pic_email' => 'nunungid8943@gmail.com','hm_name' => 'Nunung','hm_phone_number' => '81220315524','hm_email' => 'nunungid8943@gmai.com'],
            ['school_code' => '029/II/SKL-CPK','school_name' => 'RA NURUL HIDAYAH','address' => 'Dusun Mandala Rt 018 Rw 006 Desa Kertamandala Kecamatan Panjalu Kabupaten Ciamis','school_level' => 'II','pic_name' => 'Senny Anggraeni Lukmansyah','pic_position' => 'Guru / Operator','pic_phone_number' => '81321133041','pic_email' => 'sennyanggraeni30@gmail.com','hm_name' => 'Hera Nurhayati, S. PD','hm_phone_number' => '82216747810','hm_email' => 'heranurhayati932@gmail.com'],
            ['school_code' => '030/I/SKL-CPK','school_name' => 'PAUD KOBER NURUL HIDAYAH','address' => 'Dsn Ciomaslandeuh Rt.20 Rw.09 Desa Ciomas Kec Panjalu Kab Ciamis','school_level' => 'I','pic_name' => 'Agus Hamdani, S.Pd.I','pic_position' => 'Kepala/Ketua Pengelola','pic_phone_number' => '85224562073','pic_email' => 'agushamdani130780@gmail.com','hm_name' => 'Agus Hamdani, S.Pd.I','hm_phone_number' => '85224562073','hm_email' => 'agushamdani130780@gmail.com'],
            ['school_code' => '031/I/SKL-CPK','school_name' => 'POS PAUD CEMPAKA','address' => 'Ciroyom Rt19 Rw 09, Mandalare, Panjalu, Ciamis','school_level' => 'I','pic_name' => 'Dian Trisnawati','pic_position' => 'Pendidik','pic_phone_number' => '82119477221','pic_email' => 'diantrisnawati1981@gmail.com','hm_name' => 'Wahyu, S.E.','hm_phone_number' => '85220088812','hm_email' => 'pawahyu7@gmail.com'],
            ['school_code' => '032/V/SKL-CPK','school_name' => 'SMK PUTRA PANJALU','address' => 'Jalan Panjalu-Kawali Dusun Garahang Rt/Rw: 028/012 Desa Panjalu Kecamatan Panjalu','school_level' => 'V','pic_name' => 'Ade Halimah, S.Sos, Gr','pic_position' => 'Guru','pic_phone_number' => '85707152250','pic_email' => 'shanumel42@gmail.com','hm_name' => 'Drs. Ruhiyat','hm_phone_number' => '82129340240','hm_email' => 'drsruhiyat@gmail.com'],
            ['school_code' => '033/V/SKL-CPK','school_name' => 'SMK INDUSTRI PERUNGGASAN PANJALU','address' => 'Dsn. Mandala Rt/Rw 18/06 Desa Kertamandala Kec. Panjalu, Kab. Ciamis Prov. Jawa Barat','school_level' => 'V','pic_name' => 'Triyan Holilur Rohman, S.Pd.','pic_position' => 'Operator','pic_phone_number' => '81210613439','pic_email' => 'triyanholilurrohman5@gmail.com','hm_name' => 'Iwan Setiawan, S.Pd.,M.Si','hm_phone_number' => '811212130','hm_email' => 'setia.iwan.92@gmail.com'],
            ['school_code' => '034/III/SKL-CPK','school_name' => 'SDN 1 MANDALARE','address' => 'Dusun Panyingkiran Desa Mandalare Kec. Panjalu','school_level' => 'III','pic_name' => 'Fikri Maulana Herdi. S.Pd','pic_position' => 'Guru','pic_phone_number' => '81324251227','pic_email' => 'fikriaang2@gmail.com','hm_name' => 'Nandi Apandi . S.Pd.I','hm_phone_number' => '82217798366','hm_email' => 'apandinandi26@gmail.com'],
            ['school_code' => '035/I/SKL-CPK','school_name' => 'KOBER NURUL ZANNAH','address' => 'Dusun Garahang Rt/Rw 28/12 Ds. Panjalu Kec. Panjalu Kab. Ciamis','school_level' => 'I','pic_name' => 'Siti Julaeha','pic_position' => 'Kepala Sekolah','pic_phone_number' => '82123866514','pic_email' => 'aisitijulaeha47@gmail.com','hm_name' => 'Siti Julaeha','hm_phone_number' => '82123866514','hm_email' => 'aisitijulaeha47@gmail.com'],
            ['school_code' => '036/IV/SKL-CPK','school_name' => 'SMP MIFTAHUL KHOER BOARDING SCHOOL','address' => 'Jl. Kertamandala No 56 Dusun Mandala Rt 017 Rw 006 Desa Kertamandala Kecamatan Panjalu Kabupaten Ciamis','school_level' => 'IV','pic_name' => 'Lala latifah','pic_position' => 'Guru','pic_phone_number' => '85624883706','pic_email' => 'lalamufty@gmail.com','hm_name' => 'Dr siti julaeha','hm_phone_number' => '82121734025','hm_email' => 'sitijulaikha425@gmail.com'],
            ['school_code' => '037/V/SKL-CPK','school_name' => 'SMA MIFTAHUL KHOER BOARDING SCHOOL','address' => 'Jl. Kertamandala No 56 Dusun Mandala Rt 017 Rw 006 Desa Kertamandala Kecamatan Panjalu Kabupaten Ciamis','school_level' => 'V','pic_name' => 'Kiki Baehaqi Saepul millah S.Pd.','pic_position' => 'Kepala Sekolah','pic_phone_number' => '82127952012','pic_email' => 'baihakki2015@gmail.com','hm_name' => 'Kiki Baehaqi Saepul millah S. Pd','hm_phone_number' => '82127952012','hm_email' => 'baihakki2015@gmail.com'],
            ['school_code' => '038/I/SKL-CPK','school_name' => 'KOBER MIFTAHUL FALAH','address' => 'Bojong Sereh Rt/Rw 32/15,Ciomas ,Panjalu,Ciamis','school_level' => 'I','pic_name' => 'Iin inarotulhuda','pic_position' => 'Guru','pic_phone_number' => '82215008562','pic_email' => 'inarotulhuda.1984@gmail.com','hm_name' => 'Yayah rokayah','hm_phone_number' => '81023596434','hm_email' => 'teteh.taspen@gmail.com'],
            ['school_code' => '039/VI/SKL-CPK','school_name' => 'PONPES AL MUKHTARIYAH','address' => 'Panjalu','school_level' => 'VI','pic_name' => 'Unkown','pic_position' => '','pic_phone_number' => '','pic_email' => '','hm_name' => '','hm_phone_number' => '','hm_email' => ''],
            ['school_code' => '040/VI/SKL-CPK','school_name' => 'PONPES MAN BAUTTOYIBAH','address' => 'Panjalu','school_level' => 'VI','pic_name' => 'Unkown','pic_position' => '','pic_phone_number' => '','pic_email' => '','hm_name' => '','hm_phone_number' => '','hm_email' => ''],
            ['school_code' => '041/I/SKL-CPK','school_name' => 'PAUD CRISANT PURI','address' => 'Panjalu','school_level' => 'I','pic_name' => 'Unkown','pic_position' => '','pic_phone_number' => '','pic_email' => '','hm_name' => '','hm_phone_number' => '','hm_email' => ''],
            ['school_code' => '042/II/SKL-CPK','school_name' => 'RA AL ABGHANI','address' => 'Panjalu','school_level' => 'II','pic_name' => 'Unkown','pic_position' => '','pic_phone_number' => '','pic_email' => '','hm_name' => '','hm_phone_number' => '','hm_email' => ''],
            ['school_code' => '043/II/SKL-CPK','school_name' => 'TK ALRIYADOH','address' => 'Panjalu','school_level' => 'II','pic_name' => 'Unkown','pic_position' => '','pic_phone_number' => '','pic_email' => '','hm_name' => '','hm_phone_number' => '','hm_email' => ''],
            ['school_code' => '044/V/SKL-CPK','school_name' => 'MA BAHRUL ULUM','address' => 'Panjalu','school_level' => 'V','pic_name' => 'Unkown','pic_position' => '','pic_phone_number' => '','pic_email' => '','hm_name' => '','hm_phone_number' => '','hm_email' => ''],
            ['school_code' => '045/IV/SKL-CPK','school_name' => 'MTS BAHRUL ULUM','address' => 'Panjalu','school_level' => 'IV','pic_name' => 'Unkown','pic_position' => '','pic_phone_number' => '','pic_email' => '','hm_name' => '','hm_phone_number' => '','hm_email' => ''],
        ];


        foreach ($schools_data as $value) {
            School::create([
                'school_code' => $value['school_code'],
                'school_name' => $value['school_name'],
                'address' => $value['address'],
                'school_level' => $value['school_level'],
                'pic_name' => $value['pic_name'],
                'pic_position' => $value['pic_position'],
                'pic_phone_number' => $value['pic_phone_number'],
                'pic_email' => $value['pic_email'],
                'hm_name' => $value['hm_name'],
                'hm_phone_number' => $value['hm_phone_number'],
                'hm_email' => $value['hm_email'],
            ]);
        }
    }
}
